### ISSUE TITLE
自定义编译失败

### ISSUE THREAD

**Issue by xiexuetao** [muzipiao/GMOpenSSL#13]
error: cannot compute path of binary 'Path(str: "xxx/iphoneos/OpenSSL.framework/OpenSSL")' relative to that of 'xxx/iphoneos/OpenSSL.framework'

**Comment by muzipiao** [comment]
你提供的信息太少，无法判断具体原因。可尝试以下方法：
1. 使用 brew 升级 cmake；
2. 使用`git clean -xfd`删除项目文件夹下相关缓存；
3. 删除 build  和`~/Library/Developer/Xcode/DerivedData/`等缓存文件夹。
