### ISSUE TITLE
编译静态库失败

### ISSUE THREAD

**Issue by shengxiaolei** [muzipiao/GMOpenSSL#14]
OpenSSL_BUILD ./build-libssl.sh
zsh: no such file or directory: ./build-libssl.sh

按照指导操作生成不了静态文件，请大神指导一下

**Comment by muzipiao** [comment]
.......你不切换到脚本所在目录`cd xxx/yyy`，肯定找不到脚本。

1. 别麻烦了，使用`2.2.9 | 1.1.1q | x86_64 arm64 | 包含 | >= iOS 9.0`版本的 tag，里面`GMOpenSSL-2.2.9/GMFrameworks/openssl.xcframework`就是静态库，3.0.0 以上是动态库；
2. 替换 GMObjC 项目里面的`GMObjC/XCFrameworks/OpenSSL.xcframework`，把 GMObjC 编译为动态库 GMObjC.xcframework 就可以直接使用了。

https://codeload.github.com/muzipiao/GMOpenSSL/zip/refs/tags/2.2.9
