### ISSUE TITLE
麻烦podspec里加下  s.static_framework = true吧，不然pod只能静态引入

### ISSUE THREAD

**Issue by fanninghau** [muzipiao/GMOpenSSL#15]
如题，openssl是个静态库，加上这句吧

**Comment by muzipiao** [comment]
可以，谢谢指出这个细节

**Comment by fanninghau** [comment]
是不是没发布啊，拉取还是会报错

**Comment by muzipiao** [comment]
去年就更新了。
1. 更新本地仓库`pod repo update`；
2. 或者尝试指定版本`pod 'GMOpenSSL', '~> 3.1.2'`。

**Comment by fanninghau** [comment]
![Image](https://github.com/user-attachments/assets/352de7e3-c2d0-414c-87ec-d11f0e448a7f)试过了，不行呢
