### ISSUE TITLE
build 3.0.1出错

### ISSUE THREAD

**Issue by lishuailibertine** [muzipiao/GMOpenSSL#3]
M1系统
openssl-版本: 3.0.1

Undefined subroutine &main::asm called at (eval 23) line 39.
Usage: Configure [no-<cipher> ...] [enable-<cipher> ...] [-Dxxx] [-lxxx] [-Lxxx] [-fxxx] [-Kxxx] [no-hw-xxx|no-hw] [[no-]threads] [[no-]shared] [[no-]zlib|zlib-dynamic] [no-asm] [no-egd] [sctp] [386] [--prefix=DIR] [--openssldir=OPENSSLDIR] [--with-xxx[=vvv]] [--config=FILE] os/compiler[:flags]

**Comment by muzipiao** [comment]
使用 OpenSSL 1.1 系列版本，OpenSSL 3.0 是新增加的版本，废弃了很多 API，与以前的 OpenSSL 不完全兼容；
考虑市场主流加解密库仍是 1.1 系列版本，暂不升级。

**Comment by lishuailibertine** [comment]
> 使用 OpenSSL 1.1 系列版本，OpenSSL 3.0 是新增加的版本，废弃了很多 API，与以前的 OpenSSL 不完全兼容； 考虑市场主流加解密库仍是 1.1 系列版本，暂不升级。

OK，新增加的 https://www.openssl.org/docs/manmaster/man7/EVP_RAND-HMAC-DRBG.html， 害 没法用了，不知道1.1版本有可以替代的方法没
