### ISSUE TITLE
修改OPENSSL3.1.1版本编译失败，大神能帮忙编译一个吗？

### ISSUE THREAD

**Issue by xygkevin** [muzipiao/GMOpenSSL#9]

**Comment by xygkevin** [comment]
<img width="695" alt="image" src="https://github.com/muzipiao/GMOpenSSL/assets/19592642/42c293d0-4b55-4b2b-a7a8-5d29de0fcb75">

**Comment by muzipiao** [comment]
肯定会报错的，OpenSSL 3.x 与 OpenSSL 1.x 本身就不兼容，更改为 OpenSSL 1.1.x 相关版本即可。

**Comment by xygkevin** [comment]
请问需要如何修改脚本，才能实现3.1.1版本的编译呢？
